DATALOADER:
  RESIZE:
  - 320
  - 320
DATASETS:
  TEST:
  - stanford2d3d_test
  - tartanair_test
  TRAIN:
  - cities360_train
  - rgbdpano_train
DEBUG_ON: false
MODEL:
  GRAVITY_DECODER:
    IGNORE_VALUE: 72
    LOSS_TYPE: classification
    LOSS_WEIGHT: 1.0
    NAME: GravityDecoder
    NUM_CLASSES: 73
  GRAVITY_ON: true
  LATITUDE_DECODER:
    IGNORE_VALUE: -1
    LOSS_TYPE: classification
    LOSS_WEIGHT: 1.0
    NAME: LatitudeDecoder
    NUM_CLASSES: 180
  LATITUDE_ON: true
  PERSFORMER_HEADS:
    NAME: StandardPersformerHeads
  PIXEL_MEAN:
  - 103.53
  - 116.28
  - 123.675
  PIXEL_STD:
  - 1.0
  - 1.0
  - 1.0
  RECOVER_PP: false
  RECOVER_RPF: false